# Generated by Django 5.1.5 on 2025-02-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratante',
            name='mes_atrasado',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
